// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceTraders.Api.My.Account;
using SpaceTraders.Api.My.Agent;
using SpaceTraders.Api.My.Contracts;
using SpaceTraders.Api.My.Factions;
using SpaceTraders.Api.My.Ships;
using SpaceTraders.Api.My.SocketIo;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceTraders.Api.My
{
    /// <summary>
    /// Builds and executes requests for operations under \my
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::SpaceTraders.Api.My.Account.AccountRequestBuilder Account
        {
            get => new global::SpaceTraders.Api.My.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agent property</summary>
        public global::SpaceTraders.Api.My.Agent.AgentRequestBuilder Agent
        {
            get => new global::SpaceTraders.Api.My.Agent.AgentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contracts property</summary>
        public global::SpaceTraders.Api.My.Contracts.ContractsRequestBuilder Contracts
        {
            get => new global::SpaceTraders.Api.My.Contracts.ContractsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The factions property</summary>
        public global::SpaceTraders.Api.My.Factions.FactionsRequestBuilder Factions
        {
            get => new global::SpaceTraders.Api.My.Factions.FactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ships property</summary>
        public global::SpaceTraders.Api.My.Ships.ShipsRequestBuilder Ships
        {
            get => new global::SpaceTraders.Api.My.Ships.ShipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The socketIo property</summary>
        public global::SpaceTraders.Api.My.SocketIo.SocketIoRequestBuilder SocketIo
        {
            get => new global::SpaceTraders.Api.My.SocketIo.SocketIoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.My.MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.My.MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
