// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>
    /// The details of the required construction materials for a given waypoint under construction.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class ConstructionMaterial : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of units fulfilled toward the required amount.</summary>
        public int? Fulfilled { get; set; }
        /// <summary>The number of units required.</summary>
        public int? Required { get; set; }
        /// <summary>The good&apos;s symbol.</summary>
        public global::SpaceTraders.Api.Models.TradeSymbol? TradeSymbol { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.Models.ConstructionMaterial"/> and sets the default values.
        /// </summary>
        public ConstructionMaterial()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceTraders.Api.Models.ConstructionMaterial"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceTraders.Api.Models.ConstructionMaterial CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceTraders.Api.Models.ConstructionMaterial();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fulfilled", n => { Fulfilled = n.GetIntValue(); } },
                { "required", n => { Required = n.GetIntValue(); } },
                { "tradeSymbol", n => { TradeSymbol = n.GetEnumValue<global::SpaceTraders.Api.Models.TradeSymbol>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("fulfilled", Fulfilled);
            writer.WriteIntValue("required", Required);
            writer.WriteEnumValue<global::SpaceTraders.Api.Models.TradeSymbol>("tradeSymbol", TradeSymbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
