// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>Type of contract.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum Contract_type
    {
        [EnumMember(Value = "PROCUREMENT")]
        #pragma warning disable CS1591
        PROCUREMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSPORT")]
        #pragma warning disable CS1591
        TRANSPORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHUTTLE")]
        #pragma warning disable CS1591
        SHUTTLE,
        #pragma warning restore CS1591
    }
}
