// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The type of transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum MarketTransaction_type
    {
        [EnumMember(Value = "PURCHASE")]
        #pragma warning disable CS1591
        PURCHASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELL")]
        #pragma warning disable CS1591
        SELL,
        #pragma warning restore CS1591
    }
}
