// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>
    /// The ship that was scanned. Details include information about the ship that could be detected by the scanner.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class ScannedShip : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The engine of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ScannedShip_engine? Engine { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ScannedShip_engine Engine { get; set; }
#endif
        /// <summary>The frame of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ScannedShip_frame? Frame { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ScannedShip_frame Frame { get; set; }
#endif
        /// <summary>List of mounts installed in the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceTraders.Api.Models.ScannedShip_mounts>? Mounts { get; set; }
#nullable restore
#else
        public List<global::SpaceTraders.Api.Models.ScannedShip_mounts> Mounts { get; set; }
#endif
        /// <summary>The navigation information of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipNav? Nav { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipNav Nav { get; set; }
#endif
        /// <summary>The reactor of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ScannedShip_reactor? Reactor { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ScannedShip_reactor Reactor { get; set; }
#endif
        /// <summary>The public registration information of the ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipRegistration? Registration { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipRegistration Registration { get; set; }
#endif
        /// <summary>The globally unique identifier of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.Models.ScannedShip"/> and sets the default values.
        /// </summary>
        public ScannedShip()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceTraders.Api.Models.ScannedShip"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceTraders.Api.Models.ScannedShip CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceTraders.Api.Models.ScannedShip();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "engine", n => { Engine = n.GetObjectValue<global::SpaceTraders.Api.Models.ScannedShip_engine>(global::SpaceTraders.Api.Models.ScannedShip_engine.CreateFromDiscriminatorValue); } },
                { "frame", n => { Frame = n.GetObjectValue<global::SpaceTraders.Api.Models.ScannedShip_frame>(global::SpaceTraders.Api.Models.ScannedShip_frame.CreateFromDiscriminatorValue); } },
                { "mounts", n => { Mounts = n.GetCollectionOfObjectValues<global::SpaceTraders.Api.Models.ScannedShip_mounts>(global::SpaceTraders.Api.Models.ScannedShip_mounts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nav", n => { Nav = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipNav>(global::SpaceTraders.Api.Models.ShipNav.CreateFromDiscriminatorValue); } },
                { "reactor", n => { Reactor = n.GetObjectValue<global::SpaceTraders.Api.Models.ScannedShip_reactor>(global::SpaceTraders.Api.Models.ScannedShip_reactor.CreateFromDiscriminatorValue); } },
                { "registration", n => { Registration = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipRegistration>(global::SpaceTraders.Api.Models.ShipRegistration.CreateFromDiscriminatorValue); } },
                { "symbol", n => { Symbol = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ScannedShip_engine>("engine", Engine);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ScannedShip_frame>("frame", Frame);
            writer.WriteCollectionOfObjectValues<global::SpaceTraders.Api.Models.ScannedShip_mounts>("mounts", Mounts);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipNav>("nav", Nav);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ScannedShip_reactor>("reactor", Reactor);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipRegistration>("registration", Registration);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
