// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The current status of the ship</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum ShipNavStatus
    {
        [EnumMember(Value = "IN_TRANSIT")]
        #pragma warning disable CS1591
        IN_TRANSIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_ORBIT")]
        #pragma warning disable CS1591
        IN_ORBIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCKED")]
        #pragma warning disable CS1591
        DOCKED,
        #pragma warning restore CS1591
    }
}
