// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The rotation of crew shifts. A stricter shift improves the ship&apos;s performance. A more relaxed shift improves the crew&apos;s morale.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum ShipCrew_rotation
    {
        [EnumMember(Value = "STRICT")]
        #pragma warning disable CS1591
        STRICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "RELAXED")]
        #pragma warning disable CS1591
        RELAXED,
        #pragma warning restore CS1591
    }
}
