// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The ship&apos;s set speed when traveling between waypoints or systems.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum ShipNavFlightMode
    {
        [EnumMember(Value = "DRIFT")]
        #pragma warning disable CS1591
        DRIFT,
        #pragma warning restore CS1591
        [EnumMember(Value = "STEALTH")]
        #pragma warning disable CS1591
        STEALTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRUISE")]
        #pragma warning disable CS1591
        CRUISE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BURN")]
        #pragma warning disable CS1591
        BURN,
        #pragma warning restore CS1591
    }
}
