// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>
    /// Ship details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class Ship : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Ship cargo details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipCargo? Cargo { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipCargo Cargo { get; set; }
#endif
        /// <summary>A cooldown is a period of time in which a ship cannot perform certain actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.Cooldown? Cooldown { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.Cooldown Cooldown { get; set; }
#endif
        /// <summary>The ship&apos;s crew service and maintain the ship&apos;s systems and equipment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipCrew? Crew { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipCrew Crew { get; set; }
#endif
        /// <summary>The engine determines how quickly a ship travels between waypoints.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipEngine? Engine { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipEngine Engine { get; set; }
#endif
        /// <summary>The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipFrame? Frame { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipFrame Frame { get; set; }
#endif
        /// <summary>Details of the ship&apos;s fuel tanks including how much fuel was consumed during the last transit or action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipFuel? Fuel { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipFuel Fuel { get; set; }
#endif
        /// <summary>Modules installed in this ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceTraders.Api.Models.ShipModule>? Modules { get; set; }
#nullable restore
#else
        public List<global::SpaceTraders.Api.Models.ShipModule> Modules { get; set; }
#endif
        /// <summary>Mounts installed in this ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SpaceTraders.Api.Models.ShipMount>? Mounts { get; set; }
#nullable restore
#else
        public List<global::SpaceTraders.Api.Models.ShipMount> Mounts { get; set; }
#endif
        /// <summary>The navigation information of the ship.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipNav? Nav { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipNav Nav { get; set; }
#endif
        /// <summary>The reactor of the ship. The reactor is responsible for powering the ship&apos;s systems and weapons.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipReactor? Reactor { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipReactor Reactor { get; set; }
#endif
        /// <summary>The public registration information of the ship</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.Models.ShipRegistration? Registration { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.Models.ShipRegistration Registration { get; set; }
#endif
        /// <summary>The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.Models.Ship"/> and sets the default values.
        /// </summary>
        public Ship()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceTraders.Api.Models.Ship"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceTraders.Api.Models.Ship CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceTraders.Api.Models.Ship();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cargo", n => { Cargo = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipCargo>(global::SpaceTraders.Api.Models.ShipCargo.CreateFromDiscriminatorValue); } },
                { "cooldown", n => { Cooldown = n.GetObjectValue<global::SpaceTraders.Api.Models.Cooldown>(global::SpaceTraders.Api.Models.Cooldown.CreateFromDiscriminatorValue); } },
                { "crew", n => { Crew = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipCrew>(global::SpaceTraders.Api.Models.ShipCrew.CreateFromDiscriminatorValue); } },
                { "engine", n => { Engine = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipEngine>(global::SpaceTraders.Api.Models.ShipEngine.CreateFromDiscriminatorValue); } },
                { "frame", n => { Frame = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipFrame>(global::SpaceTraders.Api.Models.ShipFrame.CreateFromDiscriminatorValue); } },
                { "fuel", n => { Fuel = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipFuel>(global::SpaceTraders.Api.Models.ShipFuel.CreateFromDiscriminatorValue); } },
                { "modules", n => { Modules = n.GetCollectionOfObjectValues<global::SpaceTraders.Api.Models.ShipModule>(global::SpaceTraders.Api.Models.ShipModule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mounts", n => { Mounts = n.GetCollectionOfObjectValues<global::SpaceTraders.Api.Models.ShipMount>(global::SpaceTraders.Api.Models.ShipMount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nav", n => { Nav = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipNav>(global::SpaceTraders.Api.Models.ShipNav.CreateFromDiscriminatorValue); } },
                { "reactor", n => { Reactor = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipReactor>(global::SpaceTraders.Api.Models.ShipReactor.CreateFromDiscriminatorValue); } },
                { "registration", n => { Registration = n.GetObjectValue<global::SpaceTraders.Api.Models.ShipRegistration>(global::SpaceTraders.Api.Models.ShipRegistration.CreateFromDiscriminatorValue); } },
                { "symbol", n => { Symbol = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipCargo>("cargo", Cargo);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.Cooldown>("cooldown", Cooldown);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipCrew>("crew", Crew);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipEngine>("engine", Engine);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipFrame>("frame", Frame);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipFuel>("fuel", Fuel);
            writer.WriteCollectionOfObjectValues<global::SpaceTraders.Api.Models.ShipModule>("modules", Modules);
            writer.WriteCollectionOfObjectValues<global::SpaceTraders.Api.Models.ShipMount>("mounts", Mounts);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipNav>("nav", Nav);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipReactor>("reactor", Reactor);
            writer.WriteObjectValue<global::SpaceTraders.Api.Models.ShipRegistration>("registration", Registration);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
