// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The supply level of a trade good.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum SupplyLevel
    {
        [EnumMember(Value = "SCARCE")]
        #pragma warning disable CS1591
        SCARCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIMITED")]
        #pragma warning disable CS1591
        LIMITED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MODERATE")]
        #pragma warning disable CS1591
        MODERATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABUNDANT")]
        #pragma warning disable CS1591
        ABUNDANT,
        #pragma warning restore CS1591
    }
}
