// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum Survey_size
    {
        [EnumMember(Value = "SMALL")]
        #pragma warning disable CS1591
        SMALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "MODERATE")]
        #pragma warning disable CS1591
        MODERATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LARGE")]
        #pragma warning disable CS1591
        LARGE,
        #pragma warning restore CS1591
    }
}
