// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SpaceTraders.Api.Models
{
    /// <summary>The unique identifier of the modifier.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public enum WaypointModifierSymbol
    {
        [EnumMember(Value = "STRIPPED")]
        #pragma warning disable CS1591
        STRIPPED,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSTABLE")]
        #pragma warning disable CS1591
        UNSTABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "RADIATION_LEAK")]
        #pragma warning disable CS1591
        RADIATION_LEAK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRITICAL_LIMIT")]
        #pragma warning disable CS1591
        CRITICAL_LIMIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CIVIL_UNREST")]
        #pragma warning disable CS1591
        CIVIL_UNREST,
        #pragma warning restore CS1591
    }
}
