// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SpaceTraders.Api.My.Ships.Item.Scan.Ships;
using SpaceTraders.Api.My.Ships.Item.Scan.Systems;
using SpaceTraders.Api.My.Ships.Item.Scan.Waypoints;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SpaceTraders.Api.My.Ships.Item.Scan
{
    /// <summary>
    /// Builds and executes requests for operations under \my\ships\{shipSymbol}\scan
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class ScanRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ships property</summary>
        public global::SpaceTraders.Api.My.Ships.Item.Scan.Ships.ShipsRequestBuilder Ships
        {
            get => new global::SpaceTraders.Api.My.Ships.Item.Scan.Ships.ShipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The systems property</summary>
        public global::SpaceTraders.Api.My.Ships.Item.Scan.Systems.SystemsRequestBuilder Systems
        {
            get => new global::SpaceTraders.Api.My.Ships.Item.Scan.Systems.SystemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The waypoints property</summary>
        public global::SpaceTraders.Api.My.Ships.Item.Scan.Waypoints.WaypointsRequestBuilder Waypoints
        {
            get => new global::SpaceTraders.Api.My.Ships.Item.Scan.Waypoints.WaypointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.My.Ships.Item.Scan.ScanRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScanRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/ships/{shipSymbol}/scan", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.My.Ships.Item.Scan.ScanRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScanRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/my/ships/{shipSymbol}/scan", rawUrl)
        {
        }
    }
}
