// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceTraders.Api.My.Ships.Item.Refuel
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RefuelPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Wether to use the FUEL thats in your cargo or not.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo? FromCargo { get; set; }
#nullable restore
#else
        public global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo FromCargo { get; set; }
#endif
        /// <summary>The amount of fuel to fill in the ship&apos;s tanks. When not specified, the ship will be refueled to its maximum fuel capacity. If the amount specified is greater than the ship&apos;s remaining capacity, the ship will only be refueled to its maximum fuel capacity. The amount specified is not in market units but in ship fuel units.</summary>
        public int? Units { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody"/> and sets the default values.
        /// </summary>
        public RefuelPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fromCargo", n => { FromCargo = n.GetObjectValue<global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo>(global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo.CreateFromDiscriminatorValue); } },
                { "units", n => { Units = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo>("fromCargo", FromCargo);
            writer.WriteIntValue("units", Units);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RefuelPostRequestBody_fromCargo : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1? RefuelPostRequestBodyFromCargoMember1 { get; set; }
#nullable restore
#else
            public global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1 RefuelPostRequestBodyFromCargoMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var result = new global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody.RefuelPostRequestBody_fromCargo();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else {
                    result.RefuelPostRequestBodyFromCargoMember1 = new global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RefuelPostRequestBodyFromCargoMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RefuelPostRequestBodyFromCargoMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else {
                    writer.WriteObjectValue<global::SpaceTraders.Api.My.Ships.Item.Refuel.RefuelPostRequestBody_fromCargoMember1>(null, RefuelPostRequestBodyFromCargoMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
