// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SpaceTraders.Api.My.Contracts.Item.Fulfill
{
    /// <summary>
    /// Successfully fulfilled a contract.
    /// </summary>
    [Obsolete("This class is obsolete. Use FulfillPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FulfillResponse : global::SpaceTraders.Api.My.Contracts.Item.Fulfill.FulfillPostResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SpaceTraders.Api.My.Contracts.Item.Fulfill.FulfillResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::SpaceTraders.Api.My.Contracts.Item.Fulfill.FulfillResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SpaceTraders.Api.My.Contracts.Item.Fulfill.FulfillResponse();
        }
    }
}
#pragma warning restore CS0618
