
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AstroTrade.TUI.Views
{
    using Terminal.Gui;
    using Terminal.Gui.Views;

    public partial class ShellView
    {

        public ShellView()
        {
            InitializeComponent();
        }
    }
}
