
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AstroTrade.TUI.Views
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;

    using Terminal.Gui;
    using Terminal.Gui.Drivers;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;

    public partial class ShellView : Terminal.Gui.Views.Window
    {

        private StatusBar statusBar;

        private Shortcut f1EditMe;

        private Shortcut test;

        private void InitializeComponent()
        {
            this.statusBar = new StatusBar();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Alignment.Start;
            this.Title = "";
            this.statusBar.Width = Dim.Fill(0);
            this.statusBar.Height = 5;
            this.statusBar.X = 0;
            this.statusBar.Y = Pos.Center();
            this.statusBar.Visible = true;
            this.statusBar.Arrangement = ViewArrangement.Fixed;
            this.statusBar.CanFocus = true;
            this.statusBar.ShadowStyle = ShadowStyle.None;
            this.statusBar.Data = "statusBar";
            this.statusBar.Text = "";
            this.statusBar.TextAlignment = Alignment.Start;
            this.f1EditMe = new Shortcut(((KeyCode)(1114223u)), "F1 - Edit Me", null);
            this.statusBar.Add(this.f1EditMe);
            this.test = new Shortcut(((KeyCode)(0u)), "Test", null);
            this.statusBar.Add(this.test);
            this.Add(this.statusBar);
        }
    }
}
